-- Seed subscription plans for Beauty Hub
-- Execute this in Supabase Dashboard: https://supabase.com/dashboard/project/sbidpqhncyqmlbriyroo/sql

INSERT INTO subscription_plans (
    id, name, slug, description, price, price_monthly, price_yearly, 
    currency, billing_interval, trial_days, limits, features,
    is_active, is_public, is_highlighted, sort_order, metadata,
    created_at, updated_at
) VALUES
(
    gen_random_uuid(),
    'Starter',
    'starter',
    'Ideal para profissionais autônomos começando sua jornada digital.',
    49.90,
    49.90,
    538.80,
    'BRL',
    'monthly',
    14,
    '{"users": 2, "professionals": 1, "clients": 50, "appointments_per_month": 100, "storage_mb": 100}',
    '["appointments", "clients", "notifications"]',
    true,
    true,
    false,
    1,
    '{}',
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Professional',
    'professional',
    'Para estabelecimentos em crescimento com equipe pequena.',
    99.90,
    99.90,
    1078.80,
    'BRL',
    'monthly',
    14,
    '{"users": 5, "professionals": 3, "clients": 200, "appointments_per_month": 500, "storage_mb": 500}',
    '["appointments", "clients", "financial", "professionals", "notifications", "reports"]',
    true,
    true,
    true,
    2,
    '{"popular": true}',
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Business',
    'business',
    'Solução completa para salões e clínicas com múltiplos profissionais.',
    199.90,
    199.90,
    2158.80,
    'BRL',
    'monthly',
    14,
    '{"users": 15, "professionals": 10, "clients": 1000, "appointments_per_month": 2000, "storage_mb": 2000}',
    '["appointments", "clients", "financial", "professionals", "notifications", "reports", "api_access", "custom_branding", "advanced_analytics"]',
    true,
    true,
    false,
    3,
    '{}',
    NOW(),
    NOW()
),
(
    gen_random_uuid(),
    'Enterprise',
    'enterprise',
    'Para redes de salões e franquias com necessidades avançadas.',
    499.90,
    499.90,
    5398.80,
    'BRL',
    'monthly',
    30,
    '{"users": -1, "professionals": -1, "clients": -1, "appointments_per_month": -1, "storage_mb": 10000}',
    '["appointments", "clients", "financial", "professionals", "notifications", "reports", "api_access", "custom_branding", "advanced_analytics"]',
    true,
    false,
    false,
    4,
    '{"contact_sales": true}',
    NOW(),
    NOW()
)
ON CONFLICT (slug) DO NOTHING;
